/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				var PID = -1
				var SlotId = -1
				var Weight = -1
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						
							        CommUtils.outgreen("cargoservice | in attesa di ricevere richieste di carico")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handlealarm_load_request",cond=whenEvent("alarm"))
					transition(edgeName="t01",targetState="handle_loadRequest",cond=whenRequest("load_request"))
				}	 
				state("handle_loadRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("load(PID)"), Term.createTerm("load(PID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
									        PID = payloadArg(0).toInt()
									        CommUtils.outgreen("cargoservice | ricevuta richiesta di carico per PID:" + PID)
								request("getProduct", "product($PID)" ,"productservice" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t12",targetState="handlealarm",cond=whenEvent("alarm"))
					transition(edgeName="t13",targetState="handle_productcontainer",cond=whenReply("getProductAnswer"))
				}	 
				state("handle_productcontainer") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("product(JSonString)"), Term.createTerm("product(JSonString)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
									            val jsonStr = payloadArg(0)
									            val obj = org.json.JSONObject(jsonStr)
								
									            if(obj.getString("name").equals("wrong")) {
									            	CommUtils.outred("cargoservice | PID_NOT_REGISTERED")
									            	val Motivation = "PID_NOT_REGISTERED"
								answer("load_request", "load_refused", "reason($Motivation)"   )  
								forward("refused", "refused($Motivation)" ,name ) 
								
									            } else {
									            	
									                Weight = obj.getInt("weight")
										
										            CommUtils.outgreen("cargoservice | trovato prodotto con peso:" + Weight)
								request("validate_request", "validate($PID,$Weight)" ,"requestvalidator" )  
								
									            }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t24",targetState="handlealarm",cond=whenEvent("alarm"))
					transition(edgeName="t25",targetState="handle_load_accepted",cond=whenReply("validate_accepted"))
					transition(edgeName="t26",targetState="handle_load_refused",cond=whenReply("validate_refused"))
					transition(edgeName="t27",targetState="work",cond=whenDispatch("refused"))
				}	 
				state("handle_load_refused") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("motivation(X)"), Term.createTerm("motivation(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val RESULT = payloadArg(0).toInt()
												if(RESULT == -1) {
									        		CommUtils.outred("cargoservice | MAX_LOAD_EXCEEDED")
									        		val Motivation = "MAX_LOAD_EXCEEDED"
								answer("load_request", "load_refused", "reason($Motivation)"   )  
								
									        	} else {
									        		if(RESULT == -2) {
									        			CommUtils.outred("cargoservice | NO_FREE_SLOTS")
									        			val Motivation = "NO_FREE_SLOTS"
								answer("load_request", "load_refused", "reason($Motivation)"   )  
								
									            	}
									        	}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("handle_load_accepted") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("slot(SlotID)"), Term.createTerm("slot(SlotID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
											SlotId = payloadArg(0).toInt()
										    CommUtils.outgreen("cargoservice | product container associato allo Slot n." + SlotId)
								answer("load_request", "load_accepted", "slot($SlotId)"   )  
								forward("updategui", "updategui($PID,$SlotId,$Weight)" ,"webgui" ) 
								
								            CommUtils.outgreen("cargoservice | richiesta di carico accettata: in attesa che il product container arrivi all'IOPort")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t38",targetState="handlealarm_ioport",cond=whenEvent("alarm"))
					transition(edgeName="t39",targetState="handle_container",cond=whenDispatch("containerAtIOPort"))
				}	 
				state("handle_container") { //this:State
					action { //it:State
						
								CommUtils.outgreen("cargoservice | invio richiesta a cargorobot di trasportare il product container PID: "+ PID +" allo Slot n."+ SlotId)
						request("transport", "transport($SlotId)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t410",targetState="handlealarm",cond=whenEvent("alarm"))
					transition(edgeName="t411",targetState="work",cond=whenReply("robot_home"))
				}	 
				state("handlealarm_load_request") { //this:State
					action { //it:State
						forward("ledOn", "ledOn(ok)" ,"led" ) 
						CommUtils.outred("cargoservice | servizio interrotto")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t512",targetState="handleendalarm_load_request",cond=whenEvent("endalarm"))
				}	 
				state("handleendalarm_load_request") { //this:State
					action { //it:State
						forward("ledOff", "ledOff(ok)" ,"led" ) 
						CommUtils.outgreen("cargoservice | servizio ripristinato")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t613",targetState="handlealarm_load_request",cond=whenEvent("alarm"))
					transition(edgeName="t614",targetState="handle_loadRequest",cond=whenRequest("load_request"))
				}	 
				state("handlealarm") { //this:State
					action { //it:State
						forward("ledOn", "ledOn(ok)" ,"led" ) 
						CommUtils.outred("cargoservice | servizio interrotto")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t715",targetState="handleendalarm",cond=whenEvent("endalarm"))
				}	 
				state("handleendalarm") { //this:State
					action { //it:State
						forward("ledOff", "ledOff(ok)" ,"led" ) 
						CommUtils.outgreen("cargoservice | servizio ripristinato")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t816",targetState="handlealarm",cond=whenEvent("alarm"))
					transition(edgeName="t817",targetState="handle_productcontainer",cond=whenReply("getProductAnswer"))
					transition(edgeName="t818",targetState="handle_load_accepted",cond=whenReply("validate_accepted"))
					transition(edgeName="t819",targetState="handle_load_refused",cond=whenReply("validate_refused"))
					transition(edgeName="t820",targetState="work",cond=whenDispatch("refused"))
					transition(edgeName="t821",targetState="work",cond=whenReply("robot_home"))
				}	 
				state("handlealarm_ioport") { //this:State
					action { //it:State
						forward("ledOn", "ledOn(ok)" ,"led" ) 
						CommUtils.outred("cargoservice | servizio interrotto")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t922",targetState="handleendalarm_ioport",cond=whenEvent("endalarm"))
				}	 
				state("handleendalarm_ioport") { //this:State
					action { //it:State
						forward("ledOff", "ledOff(ok)" ,"led" ) 
						CommUtils.outgreen("cargoservice | servizio ripristinato")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t1023",targetState="handlealarm_ioport",cond=whenEvent("alarm"))
					transition(edgeName="t1024",targetState="handle_container",cond=whenDispatch("containerAtIOPort"))
				}	 
			}
		}
} 
