/* Generated by AN DISI Unibo */ 
package it.unibo.requestvalidator

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import main.java.domain.*

class Requestvalidator ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		val hold = main.java.domain.Hold.getInstance()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t013",targetState="handle_validate",cond=whenRequest("validate_request"))
				}	 
				state("handle_validate") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("validate(PID,Weight)"), Term.createTerm("validate(PID,Weight)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
											
										 val PID = payloadArg(0).toInt()
										 val  weight = payloadArg(1).toInt()
								
										 if( hold.getTotalWeight() + weight > hold.getMaxLoad() ) {
										 	CommUtils.outcyan("requestvalidator | peso massimo interno alla stiva superato")
										 	val RESULT = -1
								answer("validate_request", "validate_refused", "motivation($RESULT)"   )  
								
										 } else {
										 	var SlotID = -1
								
								        	for (slot in hold.getSlots()) {
											    if (slot.productId == -1) {
											        SlotID = slot.slotId
											        break  // esce subito dal ciclo
											    }
											}  
								
								        	if ( SlotID == -1 ) {
								        		CommUtils.outcyan("requestvalidator | slot non disponibile")
								        		val RESULT = -2
								answer("validate_request", "validate_refused", "motivation($RESULT)"   )  
								
										 	} else {
										 		CommUtils.outcyan("requestvalidator | controlli superati, richiesta accettata per il product container PID: "+ PID)
										 		hold.addContainer(SlotID, PID, weight)
								answer("validate_request", "validate_accepted", "slot($SlotID)"   )  
									
										 	}
										 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
} 
