/* Generated by AN DISI Unibo */ 
package it.unibo.clientmock

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Clientmock ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						
						    	val PROD = "{'\"productId\":31,\"name\":\"p31\",\"weight\":311'}"
						request("createProduct", "product($PROD)" ,"productservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t10",targetState="handle_createdProduct",cond=whenReply("createdProduct"))
				}	 
				state("handle_createdProduct") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("productid(ID)"), Term.createTerm("productid(ID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								              val PIDC = payloadArg(0).toInt()
								              CommUtils.outblue("Prodotto registrato con PID: " + PIDC)
								request("load_request", "load($PIDC)" ,"cargoservice" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t21",targetState="handle_loadaccepted",cond=whenReply("load_accepted"))
					transition(edgeName="t22",targetState="handle_loadrefused",cond=whenReply("load_refused"))
				}	 
				state("handle_loadaccepted") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("slot(SlotID)"), Term.createTerm("slot(SlotID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								              val ID = payloadArg(0)
								              CommUtils.outblue("Richiesta di carico accettata, product container associato allo Slot n." + ID)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handle_loadrefused") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("reason(Motivation)"), Term.createTerm("reason(Motivation)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								              val res = payloadArg(0)
								              CommUtils.outblue("Richiesta di carico rifiutata, motivo: " + res)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
