/* Generated by AN DISI Unibo */ 
package it.unibo.sonarmock

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonarmock ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						connectToMqttBroker( "tcp://localhost:1883" )
						delay(3000) 
						CommUtils.outblue("$name| rilevata sonar failure")
						//val m = MsgUtil.buildEvent(name, "alarm", "alarm(failure)" ) 
						publish(MsgUtil.buildEvent(name,"alarm","alarm(failure)").toString(), "sonarfailure" )   
						delay(2000) 
						CommUtils.outblue("$name| sonar failure terminata")
						//val m = MsgUtil.buildEvent(name, "alarm", "alarm(ok)" ) 
						publish(MsgUtil.buildEvent(name,"alarm","alarm(ok)").toString(), "sonarfailure" )   
						delay(1000) 
						CommUtils.outblue("$name| rilevato product container all'IOPort")
						forward("containerAtIOPort", "containerAtIOPort(ok)" ,"cargoservice" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
