/* Generated by AN DISI Unibo */ 
package it.unibo.sonarmock

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonarmock ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
			var Distance = 100	
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(1000) 
						CommUtils.outblue("$name| publish distanza: $Distance")
						//val m = MsgUtil.buildEvent(name, "sonardata", "distance($Distance)" ) 
						publish(MsgUtil.buildEvent(name,"sonardata","distance($Distance)").toString(), "sonar" )   
						delay(1000) 
						CommUtils.outblue("$name| publish distanza: $Distance")
						//val m = MsgUtil.buildEvent(name, "sonardata", "distance($Distance)" ) 
						publish(MsgUtil.buildEvent(name,"sonardata","distance($Distance)").toString(), "sonar" )   
						delay(1000) 
						CommUtils.outblue("$name| publish distanza: $Distance")
						//val m = MsgUtil.buildEvent(name, "sonardata", "distance($Distance)" ) 
						publish(MsgUtil.buildEvent(name,"sonardata","distance($Distance)").toString(), "sonar" )   
						delay(3000) 
						 Distance = 10  
						CommUtils.outblue("$name| publish distanza: $Distance")
						//val m = MsgUtil.buildEvent(name, "sonardata", "distance($Distance)" ) 
						publish(MsgUtil.buildEvent(name,"sonardata","distance($Distance)").toString(), "sonar" )   
						 Distance = 90  
						CommUtils.outblue("$name| publish distanza: $Distance")
						//val m = MsgUtil.buildEvent(name, "sonardata", "distance($Distance)" ) 
						publish(MsgUtil.buildEvent(name,"sonardata","distance($Distance)").toString(), "sonar" )   
						 
								Distance = 20
								while (true) {
						delay(1000) 
						//val m = MsgUtil.buildEvent(name, "sonardata", "distance($Distance)" ) 
						publish(MsgUtil.buildEvent(name,"sonardata","distance($Distance)").toString(), "sonar" )   
						
								}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
