/* Generated by AN DISI Unibo */ 
package it.unibo.webgui

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Webgui ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("webgui | Start")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handledispatch",cond=whenDispatch("updategui"))
				}	 
				state("handledispatch") { //this:State
					action { //it:State
						
									var Jsonmsg=""
						if( checkMsgContent( Term.createTerm("updategui(PID,SlotID,Weight)"), Term.createTerm("updategui(PID,SlotID,Weight)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								            val PIDC = payloadArg(0).toInt()
								            val SlotIDC=payloadArg(1).toInt()
								            val WeightC=payloadArg(2).toInt()
								            CommUtils.outblue("webgui | ricevuto aggiornamento")
								            
								            val Json = JSONObject() 
								    		Json.put("id", PIDC)
								    		Json.put("slotID", SlotIDC)
								    		Json.put("peso", WeightC)
								    		Jsonmsg = Json.toJSONString()           
								    		CommUtils.outblue("webgui | invio " + Jsonmsg)
								    		
						}
						//val m = MsgUtil.buildEvent(name, "guin", "guin($Jsonmsg)" ) 
						publish(MsgUtil.buildEvent(name,"guin","guin($Jsonmsg)").toString(), "guiin" )   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
} 
