/* Generated by AN DISI Unibo */ 
package it.unibo.sonarcontroller

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonarcontroller ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
		    var counter = 0
		    val DFREE = 50
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t018",targetState="normal",cond=whenEvent("sonardata"))
				}	 
				state("normal") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val D = payloadArg(0).toInt()
								                if(D > DFREE){
								                    counter++
								                    if(counter >= 3) {
								                    	CommUtils.outred("sonarcontroller | Sonar Failure")
								emitlocal("alarm", "alarm(failure)" ) 
								forward("sonar_failure", "sonar_failure(ok)" ,name ) 
								
								                    }
								                } else {
								                    counter = 0
								                }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t119",targetState="normal",cond=whenEvent("sonardata"))
					transition(edgeName="t120",targetState="failure",cond=whenDispatch("sonar_failure"))
				}	 
				state("failure") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val D = payloadArg(0).toInt()
								                if(D <= DFREE){
								                	CommUtils.outred("sonarcontroller | Sonar Ok")
								                	counter = 0
								forward("alarm", "alarm(ok)" ,"cargoservice" ) 
								forward("sonar_normal", "sonar_normal(ok)" ,name ) 
								
								                }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t221",targetState="failure",cond=whenEvent("sonardata"))
					transition(edgeName="t222",targetState="normal",cond=whenDispatch("sonar_normal"))
				}	 
			}
		}
} 
