/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		val helper = main.java.domain.CargoServiceHelper.getSingleton()
		
				var PID = -1	
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="handle_loadRequest",cond=whenRequest("load_request"))
				}	 
				state("handle_loadRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("load(PID)"), Term.createTerm("load(PID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
									        PID = payloadArg(0).toInt()
									        CommUtils.outgreen("cargoservice | Ricevuta richiesta di carico per PID:" + PID)
								request("getProduct", "product($PID)" ,"productservice" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t14",targetState="handle_productcontainer",cond=whenReply("getProductAnswer"))
				}	 
				state("handle_productcontainer") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("product(JSonString)"), Term.createTerm("product(JSonString)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
									            val jsonStr = payloadArg(0)
									            
									            if(jsonStr == "unknown") {
									            	CommUtils.outred("cargoservice | PID_NOT_REGISTERED")
									            	val Motivation = "PID_NOT_REGISTERED"
								answer("load_request", "load_refused", "reason($Motivation)"   )  
								forward("refused", "refused($Motivation)" ,name ) 
								
									            } else {
									            	val obj = org.json.JSONObject(jsonStr)
									                val weight = obj.getInt("weight")
										
										            CommUtils.outgreen("cargoservice | Trovato prodotto con peso:" + weight)
										
										            val RESULT = helper.handleLoadRequest(PID, weight)
										            if(RESULT >= 0){
										            	CommUtils.outgreen("cargoservice | Product container associato allo Slot n." + RESULT)
								answer("load_request", "load_accepted", "slot($RESULT)"   )  
								forward("accepted", "accepted($RESULT)" ,name ) 
								
										            } else {
										            	if(RESULT == -1) {
										            		CommUtils.outred("cargoservice | MAX_LOAD_EXCEEDED")
										            		val Motivation = "MAX_LOAD_EXCEEDED"
								answer("load_request", "load_refused", "reason($Motivation)"   )  
								forward("refused", "refused($Motivation)" ,name ) 
								
										            	} else {
										            		if(RESULT == -2) {
										            			CommUtils.outred("cargoservice | NO_FREE_SLOTS")
										            			val Motivation = "NO_FREE_SLOTS"
								answer("load_request", "load_refused", "reason($Motivation)"   )  
								forward("refused", "refused($Motivation)" ,name ) 
								
											            	}
										            	}
										            }	
									            }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t25",targetState="handle_load_accepted",cond=whenDispatch("accepted"))
					transition(edgeName="t26",targetState="s0",cond=whenDispatch("refused"))
				}	 
				state("handle_load_accepted") { //this:State
					action { //it:State
						
						              CommUtils.outgreen("cargoservice | Richiesta di carico accettata: in attesa che il product container arrivi all'IOPort'")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
