/* Generated by AN DISI Unibo */ 
package it.unibo.moveexec

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Moveexec ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				val Nome="moveexec"
				val Step=340
				var X=0
				var Y=0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("moveexec | invio richiesta ingaggiamento con basicrobot")
						request("engage", "engage($Nome,$Step)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t024",targetState="waitRequest",cond=whenReply("engagedone"))
					transition(edgeName="t025",targetState="engageerror",cond=whenReply("engagerefused"))
				}	 
				state("engageerror") { //this:State
					action { //it:State
						CommUtils.outyellow("moveexec | richiesta di ingaggiamento con basicrobot rifiutata")
						delay(5000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
				state("waitRequest") { //this:State
					action { //it:State
						CommUtils.outyellow("moveexec | in attesa di ricevere richieste di spostamento da cargorobot")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t126",targetState="work",cond=whenRequest("move"))
				}	 
				state("work") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("move(X,Y)"), Term.createTerm("move(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								 				X = payloadArg(0).toInt()
								 				Y = payloadArg(1).toInt()
								CommUtils.outyellow("moveexec | ricevuta richiesta di muovere il robot alla posizione X=$X Y=$Y")
								request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t227",targetState="handlealarm",cond=whenEvent("alarm"))
					transition(edgeName="t228",targetState="movedone",cond=whenReply("moverobotdone"))
					transition(edgeName="t229",targetState="movefailed",cond=whenReply("moverobotfailed"))
				}	 
				state("movedone") { //this:State
					action { //it:State
						CommUtils.outyellow("moveexec | robot mosso alla posizione X=$X Y=$Y")
						answer("move", "movedone", "movedone(ok)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitRequest", cond=doswitch() )
				}	 
				state("movefailed") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moverobotfailed(PLANDONE,PLANTODO)"), Term.createTerm("moverobotfailed(PLANDONE,PLANTODO)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								 				val Plan=payloadArg(1)	
								CommUtils.outyellow("moveexec | piano da eseguire: ${Plan} ")
								CommUtils.outyellow("moveexec | richiesta di muovere il robot alla posizione X=$X Y=$Y")
								request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t330",targetState="handlealarm",cond=whenEvent("alarm"))
					transition(edgeName="t331",targetState="movedone",cond=whenReply("moverobotdone"))
					transition(edgeName="t332",targetState="movefailed",cond=whenReply("moverobotfailed"))
				}	 
				state("handlealarm") { //this:State
					action { //it:State
						CommUtils.outyellow("moveexec | rilevata sonar failure, interruzione dello spostamento")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t433",targetState="handleendalarm",cond=whenEvent("alarm"))
				}	 
				state("handleendalarm") { //this:State
					action { //it:State
						CommUtils.outyellow("moveexec | fine della sonar failure, spostamento ripreso")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t534",targetState="handlealarm",cond=whenEvent("alarm"))
					transition(edgeName="t535",targetState="movedone",cond=whenReply("moverobotdone"))
					transition(edgeName="t536",targetState="movefailed",cond=whenReply("moverobotfailed"))
				}	 
			}
		}
} 
