/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				var X = 0
		 		var Y = 0
		 		var SlotId = -1
		 		val slotX = intArrayOf(1, 4, 1, 4)
		 		val slotY = intArrayOf(1, 1, 3, 3)
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(1000) 
						CommUtils.outyellow("cargorobot | start")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						CommUtils.outyellow("cargorobot | in attesa di ricevere richieste di movimento del robot da cargoservice")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t027",targetState="go_ioport",cond=whenRequest("transport"))
				}	 
				state("go_ioport") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("transport(SlotID)"), Term.createTerm("transport(SlotID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								            	SlotId = payloadArg(0).toInt()
								              	CommUtils.outyellow("cargorobot | ricevuta richiesta di carico allo Slot n."+ SlotId)
						}
						
									X=0
						 			Y=4
						CommUtils.outyellow("cargorobot | invio richiesta di spostamento del robot alla posizione X=$X Y=$Y")
						request("move", "move($X,$Y)" ,"moveexec" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t128",targetState="go_slot",cond=whenReply("movedone"))
					transition(edgeName="t129",targetState="go_ioport",cond=whenReply("movefailed"))
				}	 
				state("go_slot") { //this:State
					action { //it:State
						
									X = slotX[SlotId]
						 			Y = slotY[SlotId]
						CommUtils.outyellow("cargorobot | carico del product container dall'IOPort")
						delay(4000) 
						CommUtils.outyellow("cargorobot | invio richiesta di spostamento del robot alla posizione X=$X Y=$Y")
						request("move", "move($X,$Y)" ,"moveexec" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t230",targetState="go_home",cond=whenReply("movedone"))
					transition(edgeName="t231",targetState="go_slot",cond=whenReply("movefailed"))
				}	 
				state("go_home") { //this:State
					action { //it:State
						
									X=0
						 			Y=0
						CommUtils.outyellow("cargorobot | scarico del product container all'Unload Position dello Slot n.$SlotId")
						delay(4000) 
						CommUtils.outyellow("cargorobot | invio richiesta di spostamento del robot alla posizione X=$X Y=$Y")
						request("move", "move($X,$Y)" ,"moveexec" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t332",targetState="robotAtHome",cond=whenReply("movedone"))
					transition(edgeName="t333",targetState="go_home",cond=whenReply("movefailed"))
				}	 
				state("robotAtHome") { //this:State
					action { //it:State
						CommUtils.outyellow("cargorobot | operazione completata, robot tornato alla HOME")
						answer("transport", "robot_home", "robot_home(ok)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
} 
