/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t117",targetState="go_ioport",cond=whenRequest("transport"))
					interrupthandle(edgeName="t118",targetState="handlealarm",cond=whenEvent("alarm"),interruptedStateTransitions)
				}	 
				state("go_ioport") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("transport(SlotID)"), Term.createTerm("transport(SlotID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								            	val SlotId = payloadArg(0).toInt()
								              	CommUtils.outyellow("cargorobot | ricevuta richiesta di carico allo Slot n."+ SlotId)
								delay(3000) 
								
											CommUtils.outyellow("cargorobot | trasporto completato, il robot e' tornato alla HOME")
								answer("transport", "robot_home", "robot_home(ok)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("handlealarm") { //this:State
					action { //it:State
						if(  currentMsg.msgContent() == "alarm(ok)"  
						 ){CommUtils.outyellow("cargorobot | servizio ripristinato")
						returnFromInterrupt(interruptedStateTransitions)
						}
						else
						 {CommUtils.outyellow("cargorobot | servizio interrotto")
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t219",targetState="handlealarm",cond=whenEvent("alarm"))
				}	 
			}
		}
} 
