/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
		    var counter = 0
		    var counterIO = 0
		    val DFREE = 50
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="normal",cond=whenDispatch("sonardata"))
				}	 
				state("normal") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val D = payloadArg(0).toInt()
								                if(D > DFREE){
								                    counter++
								                    if(counter >= 3) {
								                    	CommUtils.outred("sonar | rilevata sonar failure")
								emit("alarm", "alarm(failure)" ) 
								forward("sonar_failure", "sonar_failure(ok)" ,name ) 
								
								                    }
								                } else {
								                	if(D < DFREE/2)
								                    {
								                    	counterIO++
								                    	if(counterIO == 3) {
									                    	CommUtils.outgreen("sonar | rilevata presenza di un container all'IOPort")
								forward("containerAtIOPort", "containerAtIOPort(ok)" ,"cargoservice" ) 
								
								                    	}
								                    } else {
								                    	counter = 0
								                    	counterIO = 0
								                    }
								                }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t11",targetState="normal",cond=whenDispatch("sonardata"))
					transition(edgeName="t12",targetState="failure",cond=whenDispatch("sonar_failure"))
				}	 
				state("failure") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val D = payloadArg(0).toInt()
								                if(D <= DFREE){
								                	CommUtils.outred("sonar | sonar failure terminata")
								                	counter = 0
								                	
								                	if(D < DFREE/2) {
								            			counterIO = 1
								                	}
								emit("endalarm", "endalarm(ok)" ) 
								forward("sonar_normal", "sonar_normal(ok)" ,name ) 
								
								                }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t23",targetState="failure",cond=whenDispatch("sonardata"))
					transition(edgeName="t24",targetState="normal",cond=whenDispatch("sonar_normal"))
				}	 
			}
		}
} 
